### ISSUE TITLE
Text shouldn't be selectable

### ISSUE THREAD

**Issue by samuelli** [Manohar-Gunturu/calendar-lite#1]
Particularly on Chrome for Android, if Now on Tap is enabled, it'll continue to trigger every time a tap occurs.

**Comment by Manohar-Gunturu** [comment]
Updated check it out https://beta.webcomponents.org/element/Manohar-Gunturu/calendar-lite.
Feel free to notify any more bugs

**Comment by samuelli** [comment]
Awesome, works!

By the way this element looks amazing, so fast!
