### ISSUE TITLE
You will want to choose a license so people know they can safely use your code!

### ISSUE THREAD

**Issue by ghost** [Manohar-Gunturu/calendar-lite#2]
Code is copyrighted by default with All Rights Reserved. You don't even have to explicitly say so. I am wary about using this plugin on my site as I do not know what I can or cannot do legally. Now, I did do a search and found bower.json says the code is MIT license. If that is so, you will want to create a license file to show that. If not, you can use https://github.com/blog/1530-choosing-an-open-source-license to help you choose a license and then create the license file. Thank You!

**Comment by Manohar-Gunturu** [comment]
Yes this is under MIT license. I am just adding LICENSE file check it out. Thank you !. Feel free to notify any further issues.

**Comment by ghost** [comment]
Thank you for adding the license file! I will notify you if I find any further issues!
